name: Terraform Apply

on:
  workflow_dispatch:
  #push:
    #branches: [ "main", "staging" ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}  # staging/prod env protection

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/github-oidc-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Select tfvars based on branch
        id: vars
        run: |
          if [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "tfvars=envs/staging.tfvars" >> $GITHUB_OUTPUT
          else
            echo "tfvars=envs/prod.tfvars" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Plan
        run: terraform plan -var-file=${{ steps.vars.outputs.tfvars }} -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
